## Screen size constants

DEFAULT_DISP_WIDTH = 320

# ViewPort 1
# Logo area
WIDTH1 = 384
HEIGHT1 = 160
DISPL_WIDTH1 = DEFAULT_DISP_WIDTH
DISPL_HEIGHT1 = 79

# ViewPort 2
# Checkerboard & bobs area
ANIM_STRIPE = 10
WIDTH2 = 320
DISPL_WIDTH2 = DEFAULT_DISP_WIDTH
DISPL_HEIGHT2 = 150
HEIGHT2 = (DISPL_HEIGHT2 * ANIM_STRIPE)                        

# ViewPort 2b
ANIM_STRIPEb = 8
WIDTH2b = 384
DISPL_WIDTH2b = DEFAULT_DISP_WIDTH
DISPL_HEIGHT2b = 150
HEIGHT2b = (DISPL_HEIGHT2b * ANIM_STRIPEb) 

# ViewPort 3
WIDTH3 = DEFAULT_DISP_WIDTH
DISPL_HEIGHT3 = 13
HEIGHT3 = (DISPL_HEIGHT3 << 1)

#define COLOUR_PURPLE_DARK (ULONG)0x2a1221
#define COLOUR_PURPLE (ULONG)0x4a2251
#define COLOUR_PURPLE_LIGHT (ULONG)0x5F004B

#define COLOUR_PURPLE_RGB4 (UWORD)0x425
#define COLOUR_PURPLE_DARK_RGB4 (UWORD)0x213