#ifndef DEMO_MODE_SWITCHES
#define DEMO_MODE_SWITCHES

#define	DMODE_SW_INTRO	0
#define	DMODE_SW_UBOB	1
#define	DMODE_SW_CLEAR_FROM_TOP	2
#define	DMODE_SW_CLEAR_FROM_BOTTOM	3
#define DMODE_SW_NEXT_UBOB 4
#define DMODE_SW_CHANGE_UBOB_PALETTE 5
#define DMODE_SW_FADE_IN_MLOGO 6
#define DMODE_SW_FADE_OUT_MLOGO 7
#define DMODE_SW_FADE_IN_ZLOGO 8
#define DMODE_SW_FADE_OUT_ZLOGO 9

#define	TEXTMODE_SW_WAIT 0
#define	TEXTMODE_SW_CLEAR 1
#define	TEXTMODE_SW_PRECALC 2
#define	TEXTMODE_SW_DRAW 3
#define TEXTMODE_SW_DRAW_LOOP 4
#define TEXTMODE_SW_SCROLL 5

#define UBOB_SW_SPHERE 0
#define UBOB_SW_TORUS 1
#endif