#ifndef DEMO_MODE_SWITCHES
#define DEMO_MODE_SWITCHES

#define	DMODE_SW_INTRO	0
#define	DMODE_SW_UBOB	1
#define	DMODE_SW_CLEAR_FROM_TOP	2
#define	DMODE_SW_CLEAR_FROM_BOTTOM	3
#define DMODE_SW_NEXT_UBOB 4

#define	TEXTMODE_SW_WAIT 0
#define	TEXTMODE_SW_CLEAR 1
#define	TEXTMODE_SW_PRECALC 2
#define	TEXTMODE_SW_DRAW 3
#define TEXTMODE_SW_SCROLL 4
#endif